name: Auto-Merge Dependabot

on:
  push:
    branches:
      - '**'
    
permissions:
  contents: write
  pull-requests: write
  packages: read
  
jobs:
  dependabot:
    name: 'Dependabot'
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.dependabot-token}}
